services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: osa_db
      POSTGRES_USER: osa_user
      POSTGRES_PASSWORD: osa_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
