server {
    if ($host = preprod.osa-observatory.africa) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name preprod.osa-observatory.africa;
    return 301 https://$host$request_uri;


}

server {
    listen 443 ssl;
    server_name preprod.osa-observatory.africa;
    ssl_certificate /etc/letsencrypt/live/preprod.osa-observatory.africa/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/preprod.osa-observatory.africa/privkey.pem; # managed by Certbot

    auth_basic "OSA Observatory -- Acces Comite";
    auth_basic_user_file /etc/nginx/.htpasswd;

    root /var/www/preprod;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
