server {
    server_name open.osa-observatory.africa;
    root /var/www/portal;
    index index.html;
    location / { try_files $uri $uri/ /index.html; }
    location /.well-known/acme-challenge/ { root /var/www/certbot; }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/open.osa-observatory.africa/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/open.osa-observatory.africa/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = open.osa-observatory.africa) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name open.osa-observatory.africa;
    return 404; # managed by Certbot


}