-- OSA Observatory — Classification indicator_group — Sprint 22
-- Taxonomie : PHYSIQUE / EXPLOITATION / PRESSION / TRAJECTOIRE
-- 206 indicateurs sur 10 piliers

-- PECO
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('ECO_GDP','ECO_PRO','ECO_IND','ECO_SME','ECO_AGR');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('ECO_EXP','ECO_FDI','ECO_INV','ECO_TAX','ECO_EMP','ECO_PUBLIC_REV','ECO_DIV','ECO_VAF','ECO_EXB','ECO_INB');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('ECO_IMP','ECO_INF','ECO_UNE','ECO_GRW','ECO_INFORMAL_RATE','ECO_INFORMAL_NB','ECO_INFORMAL_MICRO','ECO_INFORMAL_NAG');
UPDATE rf.indicators SET indicator_group = 'TRAJECTOIRE' WHERE code IN ('ECO_PUBLIC_LEAKAGE','ECO_TAX_EFFICIENCY','ECO_FORMAL_TRAJECTORY');

-- PENV
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('ENV_FOR','ENV_WAT','ENV_SOL','ENV_BIO','ENV_ECO');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('ENV_ENR','ENV_ENE','ENV_PRO','ENV_FIS','ENV_WAS');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('ENV_CO2','ENV_LAN','ENV_POL','ENV_RSK','ENV_ADA','ENV_DEF','ENV_REF');

-- PGEO
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('GEO_DIP','GEO_ORG','GEO_ALL','GEO_TRD','GEO_POW','GEO_SOF');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('GEO_PEA','GEO_CUL','GEO_NET','GEO_RES','GEO_SOVEREIGN_MARGIN');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('GEO_CON','GEO_SAN','GEO_MIG','GEO_CONF','GEO_TER','PGEO_CIV','PGEO_EVT','PGEO_FAT','PGEO_INS','PGEO_INT','PGEO_PEAK','PGEO_PRE','PGEO_SPR','PGEO_STR','PGEO_TRD');

-- PHUM
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('HUM_POP','HUM_HEA','HUM_LIT','HUM_EDU','HUM_FOO');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('HUM_HEA2','HUM_SAN','HUM_WAT','HUM_DIG','HUM_GEN','HUM_SOC');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('HUM_INF','HUM_POV','HUM_MIG','HUM_RES');

-- PMIL
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('MIL_PER','MIL_RES','MIL_EQU','MIL_IND','PMIL_ARMED_FORCES','MIL_EXP','MIL_EXP_PC','MIL_EXP_PCT','PMIL_DEF_BUDGET_GDP','PMIL_DEF_BUDGET_GOV');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('MIL_LOG','MIL_INT','MIL_MIS','MIL_BRD','MIL_STR','MIL_CYB','PMIL_GCI_CYBER');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('MIL_DEP','MIL_TER','MIL_SEC','MIL_STB','PMIL_ARMS_IMPORT','PMIL_ARMS_EXPORT','PMIL_GTI_TERROR','PMIL_HOMICIDE_RATE');

-- PMIN
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('MIN_CERT','MIN_COM','MIN_DIV','MIN_EMP','MIN_INV','MIN_TECH','MIN_TRAC');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('MIN_LEAKAGE_RISK');

-- PMON
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('MON_RES','MON_M2','MON_CUR','MON_IND','MON_CTRL','MON_GDP_CURRENT');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('MON_FIN','MON_DIG','MON_CRY','MON_CAP','MON_CHG','MON_PAY','MON_STB');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('MON_DET','MON_EXT','MON_INF','MON_INT','MON_EXR','MON_AUT');
UPDATE rf.indicators SET indicator_group = 'TRAJECTOIRE' WHERE code IN ('MON_IFF_PRESSURE');

-- PNUM
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('NUM_INT','NUM_MOB','NUM_FIB','NUM_DAT','NUM_SAT','PNUM_BROADBAND_FIXED','PNUM_BROADBAND_MOBILE','PNUM_INTERNET_USERS','PNUM_MOBILE_SUBSCRIPTIONS','PNUM_SECURE_SERVERS');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('NUM_GOV','NUM_REG','NUM_DIG','NUM_FIN','NUM_CLO','NUM_STU','PNUM_EGDI_EGOV','PNUM_EGDI_HUMAN_CAP','PNUM_EGDI_ONLINE_SVC','PNUM_TERTIARY_ENROLL');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('NUM_CYB','NUM_RES','NUM_AI','NUM_DAT2','PNUM_GCI_DIGITAL','PNUM_ITU_REG_ENV');

-- PRES
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('PRES_EN_RESERVE','PRES_EN_ELEC_PROD','PRES_EN_FOSSIL','PRES_EN_PROD_TOT','PRES_WA_RES_TOTAL','PRES_WA_RES_PC','PRES_WA_INTERNAL','PRES_WA_GROUND','PRES_WA_SURFACE','PRES_WA_STORAGE','PRES_BEN','PRES_CAR','PRES_PRB');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('PRES_EN_CAPACITY','PRES_EN_CAP_PC','PRES_EN_RENEW_SHARE','PRES_WATER_AGRI','PRES_WATER_FRESH','PRES_WATER_WITHDRAWAL','PRES_RENEW_CAP_IRENA','PRES_RENEW_SHARE_FEC','PRES_ENRG_PROD_IEA','PRES_ENRG_USE_CAP');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('PRES_OIL_RENTS','PRES_GAS_RENTS','PRES_FOSSIL_RENTS_EIA','PRES_EN_STABILITY','PRES_WA_VARIABILITY');

-- PTRA
UPDATE rf.indicators SET indicator_group = 'PHYSIQUE' WHERE code IN ('PTRA_RD_TOTAL','PTRA_RD_PAVED','PTRA_RD_DENSITY','PTRA_PORT_CAP','PTRA_AIR_AIRPORTS');
UPDATE rf.indicators SET indicator_group = 'EXPLOITATION' WHERE code IN ('PTRA_AIR_PASSENGERS','PTRA_AIR_CARGO','PTRA_AIR_CONNECT','PTRA_AIR_HUB','PTRA_PORT_CONNECT','PTRA_LOG_LPI','PTRA_MULTI');
UPDATE rf.indicators SET indicator_group = 'PRESSION' WHERE code IN ('PTRA_RD_QUALITY','PTRA_RD_CONNECT','PTRA_RD_STABILITY');

-- Verification finale
SELECT indicator_group, COUNT(*) as nb
FROM rf.indicators WHERE is_active = true
GROUP BY indicator_group ORDER BY indicator_group NULLS LAST;
