import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { getStructuralObs } from '../api/structural'
import { useLang } from '../i18n/useLang'
import './IosaDetail.css'

// Années de la fenêtre de publication officielle
const PUB_YEARS = [2020, 2021, 2022, 2023, 2024]

// Labels publics des indicateurs (sans codes internes)
const INDICATOR_ABOUT = {
  PHUM_VALUE_CAPTURE: {
    fr: {
      label: 'Capture de valeur du capital humain',
      about: "Cet indicateur observe dans quelle mesure un État retient sur son territoire la valeur économique générée par son capital humain — médecins, ingénieurs, cadres. Une valeur faible signale une fuite structurelle de compétences et de revenus.",
      source: 'Banque mondiale — données primaires',
      coverage: '54 pays · 2010–2024',
      note: null,
    },
    en: {
      label: 'Human capital value capture',
      about: "This indicator observes the extent to which a state retains on its territory the economic value generated by its human capital — doctors, engineers, executives. A low value signals a structural outflow of skills and income.",
      source: 'World Bank — primary data',
      coverage: '54 countries · 2010–2024',
      note: null,
    }
  },
  PMIN_VALUE_LEAKAGE: {
    fr: {
      label: 'Fuite de valeur minière',
      about: "Cet indicateur mesure l'écart entre la valeur brute des ressources minérales exportées et la valeur ajoutée retenue dans le pays producteur. Un écart élevé traduit une extraction de richesse sans transformation locale.",
      source: 'CEPII BACI HS92 — données primaires',
      coverage: '54 pays · 2010–2024',
      note: null,
    },
    en: {
      label: 'Mineral value leakage',
      about: "This indicator measures the gap between the gross value of exported mineral resources and the value added retained in the producing country. A high gap reflects wealth extraction without local processing.",
      source: 'CEPII BACI HS92 — primary data',
      coverage: '54 countries · 2010–2024',
      note: null,
    }
  },
  PMIN_SMUGGLING_SIGNAL_RANK: {
    fr: {
      label: 'Signal de contrebande minière',
      about: "Cet indicateur documente un signal ordinal de suspicion de contrebande minière, construit à partir du croisement des flux commerciaux déclarés et des estimations de production. Il ne désigne aucune responsabilité — il identifie une configuration méritant une investigation complémentaire.",
      source: 'BACI × USGS — données primaires croisées',
      coverage: '37 pays · 2016–2021',
      note: {
        fr: 'Série partielle — couverture 2016–2021 pour 37 pays. Les années hors de cette fenêtre ne disposent pas de données observées.',
        en: 'Partial series — 2016–2021 coverage for 37 countries. Years outside this window have no observed data.'
      }
    },
    en: {
      label: 'Mineral smuggling signal',
      about: "This indicator documents an ordinal smuggling suspicion signal, built from the cross-referencing of declared trade flows and production estimates. It assigns no responsibility — it identifies a configuration warranting further investigation.",
      source: 'BACI × USGS — cross-referenced primary data',
      coverage: '37 countries · 2016–2021',
      note: {
        fr: 'Série partielle — couverture 2016–2021 pour 37 pays. Les années hors de cette fenêtre ne disposent pas de données observées.',
        en: 'Partial series — 2016–2021 coverage for 37 countries. Years outside this window have no observed data.'
      }
    }
  }
}

const INDICATOR_ORDER = ['PHUM_VALUE_CAPTURE', 'PMIN_VALUE_LEAKAGE', 'PMIN_SMUGGLING_SIGNAL_RANK']

function getTrend(data, years) {
  const vals = years.map(y => data.find(d => d.year === y)?.observed_value).filter(v => v != null)
  if (vals.length < 2) return '→'
  const delta = vals[vals.length - 1] - vals[0]
  if (delta > 0.05) return '↗'
  if (delta < -0.05) return '↘'
  return '→'
}

function StatusBadge({ status, lang }) {
  const labels = {
    OBSERVED:   { fr: 'Observé',   en: 'Observed' },
    COLLECTING: { fr: 'Collecte',  en: 'Collecting' },
    PARTIAL:    { fr: 'Partiel',   en: 'Partial' },
  }
  const s = status || 'COLLECTING'
  return (
    <span className={`iosa-status-badge iosa-status-${s}`}>
      {labels[s]?.[lang] || s}
    </span>
  )
}

function PubBadge({ status }) {
  const labels = { OFFICIAL: 'Officiel', PRELIMINARY: 'Prél.', null: '—' }
  const cls = status ? `iosa-pub-${status}` : 'iosa-pub-null'
  return <span className={`iosa-pub-badge ${cls}`}>{labels[status] || '—'}</span>
}

function IndicatorDetail({ code, data, lang }) {
  const about = INDICATOR_ABOUT[code]?.[lang]
  if (!about) return null

  // Toutes les années disponibles triées
  const allYears = [...new Set(data.map(d => d.year))].sort((a,b) => a - b)
  // Années de publication officielle présentes dans les données
  const pubYears = allYears.filter(y => PUB_YEARS.includes(y))

  // Variation sur la fenêtre de publication
  const pubVals = pubYears.map(y => data.find(d => d.year === y)?.observed_value).filter(v => v != null)
  const variationPct = pubVals.length >= 2
    ? ((pubVals[pubVals.length-1] - pubVals[0]) / Math.abs(pubVals[0])) * 100
    : null

  return (
    <div className="iosa-block iosa-indicator-block">
      <h2 className="iosa-block-title">{about.label}</h2>

      <div className="iosa-indicator-meta">
        <div className="iosa-indicator-meta-item">
          <span className="iosa-meta-label">{lang === 'fr' ? 'Source' : 'Source'}</span>
          <span className="iosa-meta-value">{about.source}</span>
        </div>
        <div className="iosa-indicator-meta-item">
          <span className="iosa-meta-label">{lang === 'fr' ? 'Couverture' : 'Coverage'}</span>
          <span className="iosa-meta-value">{about.coverage}</span>
        </div>
      </div>

      <p className="iosa-block-text" style={{ marginBottom: 16 }}>{about.about}</p>

      {about.note && (
        <p className="iosa-block-text" style={{ background: '#fff8e1', padding: '8px 12px', borderRadius: 4, fontSize: '.88rem', color: '#7D4800', marginBottom: 16 }}>
          ⚠ {about.note[lang] || about.note.fr}
        </p>
      )}

      {/* Trajectoire sur les années disponibles */}
      <h3 style={{ fontSize: '.95rem', color: '#1a3c5e', marginBottom: 8, marginTop: 0 }}>
        {lang === 'fr' ? 'Trajectoire observée' : 'Observed trajectory'}
      </h3>
      <table className="iosa-trajectory-table">
        <thead>
          <tr>
            <th>{lang === 'fr' ? 'Année' : 'Year'}</th>
            <th>{lang === 'fr' ? 'Valeur observée' : 'Observed value'}</th>
            <th>{lang === 'fr' ? 'Valeur brute' : 'Raw value'}</th>
            <th>{lang === 'fr' ? 'Publication' : 'Publication'}</th>
          </tr>
        </thead>
        <tbody>
          {allYears.map(y => {
            const row = data.find(d => d.year === y)
            const isOfficial = PUB_YEARS.includes(y)
            const rowClass = row?.publication_status === 'OFFICIAL' ? 'row-official'
              : isOfficial ? 'row-partial' : 'row-outside'
            return (
              <tr key={y} className={rowClass}>
                <td>{y}</td>
                <td>{row?.observed_value != null ? row.observed_value.toFixed(3) : '—'}</td>
                <td>{row?.raw_value != null ? row.raw_value.toFixed(3) : '—'}</td>
                <td><PubBadge status={row?.publication_status || null} /></td>
              </tr>
            )
          })}
        </tbody>
      </table>

      {variationPct !== null && (
        <p className="iosa-variation">
          {lang === 'fr' ? 'Variation 2020–2024 : ' : 'Variation 2020–2024: '}
          <strong>{variationPct >= 0 ? '+' : ''}{variationPct.toFixed(1)}%</strong>
        </p>
      )}
    </div>
  )
}

export default function IosaDetail() {
  const { iso3 } = useParams()
  const { lang } = useLang()
  const [data, setData] = useState(null)
  const [selected, setSelected] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    setLoading(true)
    setError(null)
    setSelected(null)
    getStructuralObs(iso3)
      .then(d => setData(d))
      .catch(e => setError(e.message))
      .finally(() => setLoading(false))
  }, [iso3])

  if (loading) return <div className="page-loading">{lang === 'fr' ? 'Chargement...' : 'Loading...'}</div>
  if (error)   return <div className="page-error">{lang === 'fr' ? 'Erreur' : 'Error'}: {error}</div>

  // Grouper par indicateur
  const byIndicator = {}
  if (data) {
    data.forEach(row => {
      if (!byIndicator[row.indicator_code]) byIndicator[row.indicator_code] = []
      byIndicator[row.indicator_code].push(row)
    })
  }

  const hasData = Object.keys(byIndicator).length > 0

  return (
    <div className="iosa-detail-page">
      <div className="iosa-detail-header">
        <h1 className="iosa-detail-title">
          {lang === 'fr' ? 'Observations Souveraines' : 'Sovereign Observations'} — {iso3}
        </h1>
        <Link to={`/country/${iso3}`} className="back-link">← {iso3}</Link>
      </div>

      {/* À propos de l'IOSA */}
      <div className="iosa-block iosa-block-about">
        <h2 className="iosa-block-title">
          {lang === 'fr' ? 'Observations Souveraines Autonomes' : 'Autonomous Sovereign Observations'}
        </h2>
        <p className="iosa-block-text">
          {lang === 'fr'
            ? "Les Observations Souveraines Autonomes identifient, documentent et suivent des phénomènes ayant une matérialité mesurable et présentant un intérêt stratégique pour la souveraineté d'un État. Chaque observation repose sur une source primaire unique, auditée et reproductible. Ces observations ne produisent ni classement, ni jugement, ni causalité — elles mettent en évidence des réalités objectivables dont l'analyse peut conduire à des investigations complémentaires."
            : "Autonomous Sovereign Observations identify, document and track phenomena with measurable materiality that are of strategic interest for a state's sovereignty. Each observation relies on a single, audited and reproducible primary source. These observations produce no ranking, judgment, or causal claim — they highlight objective realities whose analysis may lead to further investigation."}
        </p>
      </div>

      {!hasData ? (
        <p className="iosa-detail-empty">
          {lang === 'fr' ? 'Aucune observation disponible pour ce pays.' : 'No observations available for this country.'}
        </p>
      ) : (
        <>
          {/* Vue synthétique — tableau des observations */}
          {!selected && (
            <div className="iosa-block">
              <h2 className="iosa-block-title">
                {lang === 'fr' ? 'Observations disponibles' : 'Available observations'}
              </h2>
              <table className="iosa-obs-table">
                <thead>
                  <tr>
                    <th>{lang === 'fr' ? 'Observation' : 'Observation'}</th>
                    <th>{lang === 'fr' ? 'Statut' : 'Status'}</th>
                    <th>{lang === 'fr' ? 'Tendance 2020–2024' : 'Trend 2020–2024'}</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {INDICATOR_ORDER.map(code => {
                    const rows = byIndicator[code]
                    if (!rows) return null
                    const about = INDICATOR_ABOUT[code]?.[lang]
                    const latestStatus = rows.find(r => PUB_YEARS.includes(r.year))?.value_status || 'COLLECTING'
                    const trend = getTrend(rows, PUB_YEARS)
                    return (
                      <tr key={code}>
                        <td>
                          <span className="iosa-obs-name">{about?.label || code}</span>
                          <span className="iosa-obs-pillar">{rows[0]?.pillar_code}</span>
                        </td>
                        <td><StatusBadge status={latestStatus} lang={lang} /></td>
                        <td style={{ fontSize: '1.2rem', textAlign: 'center' }}>{trend}</td>
                        <td>
                          <button className="iosa-btn-voir" onClick={() => setSelected(code)}>
                            {lang === 'fr' ? 'Voir →' : 'View →'}
                          </button>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          )}

          {/* Vue détail d'un indicateur */}
          {selected && (
            <>
              <button className="iosa-back-top" onClick={() => setSelected(null)}>
                ← {lang === 'fr' ? 'Toutes les observations' : 'All observations'}
              </button>
              <IndicatorDetail
                code={selected}
                data={byIndicator[selected] || []}
                lang={lang}
              />
            </>
          )}
        </>
      )}

      <p className="iosa-disclaimer">
        {lang === 'fr'
          ? "Les observations souveraines autonomes ne constituent pas un jugement sur la gouvernance des États. Elles documentent des phénomènes objectivables dont l'analyse relève de la responsabilité des décideurs, chercheurs et institutions."
          : "Autonomous sovereign observations do not constitute a judgment on state governance. They document objective phenomena whose analysis is the responsibility of decision-makers, researchers, and institutions."}
      </p>
    </div>
  )
}
